# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 21:45
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=250)),
                ('book_cover', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/Desktop/musicweb/media'), upload_to=b'')),
                ('author', models.CharField(max_length=250)),
                ('mp3_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/Desktop/musicweb/media'), upload_to=b'')),
                ('doc_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/Desktop/musicweb/media'), upload_to=b'')),
                ('pdf_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/Desktop/musicweb/media'), upload_to=b'')),
                ('txt_file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/Desktop/musicweb/media'), upload_to=b'')),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookshelf_label', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('bookshelf_logo', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/Desktop/musicweb/media'), upload_to=b'')),
                ('public', models.BooleanField(default=False)),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/Desktop/musicweb/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/Desktop/musicweb/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='song',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/Desktop/musicweb/media'), upload_to=b''),
        ),
        migrations.AddField(
            model_name='book',
            name='bookshelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Bookshelf'),
        ),
    ]
