# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180515_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='bookshelf',
            new_name='bookshelfs',
        ),
    ]
