# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 22:33
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20180515_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/myGit/newWords2/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/myGit/newWords2/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='book',
            name='doc_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/myGit/newWords2/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='book',
            name='mp3_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/myGit/newWords2/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/myGit/newWords2/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='book',
            name='txt_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/myGit/newWords2/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='bookshelf_logo',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/myGit/newWords2/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/myGit/newWords2/media'), upload_to=b''),
        ),
        migrations.AlterField(
            model_name='song',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=b'/home/zeynelabidin/myGit/newWords2/media'), upload_to=b''),
        ),
    ]
